services:
  # prototype server
  protos:
    depends_on:
      - redis
    build:
      context: ..
      dockerfile: infra/protos.dockerfile
    command:
      [
        "/usr/local/bin/app",
        "--config",
        "/usr/src/app/cmd/protos/config/local-docker.yaml",
      ]
    ports:
      - 8080:8080
  redis:
    image: redis:7.4-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
